// Generated by scripts/build-hero-assets.mjs — do not edit.
// Filenames are content-addressed so /hero/* can be cached immutably.

export const heroAssets = {
  avifSrcSet: "/hero/artwork-480.dbe96cc1.avif 480w, /hero/artwork-640.2bc15f09.avif 640w, /hero/artwork-960.60c3cfa0.avif 960w, /hero/artwork-1280.13c04b8e.avif 1280w, /hero/artwork-1600.11d12ea1.avif 1600w, /hero/artwork-2038.82fdbedd.avif 2038w",
  webpSrcSet: "/hero/artwork-480.38d2d7ab.webp 480w, /hero/artwork-640.b00acf1f.webp 640w, /hero/artwork-960.90dca022.webp 960w, /hero/artwork-1280.cacb339f.webp 1280w, /hero/artwork-1600.fee7b451.webp 1600w, /hero/artwork-2038.43b42b51.webp 2038w",
  fallback: "/hero/artwork-1280.d597db13.png",
  socketMask: "/hero/socket-mask.d3febd12.webp",
  pupil: "/hero/pupil.f34b6b86.png",
} as const;
